// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq1x4PH6ENI0TyC2tN4nl2yzwmUJnn5Yg',
    appId: '1:757098419210:web:2eb4fa4bb291b46786fbf3',
    messagingSenderId: '757098419210',
    projectId: 'whatsapp-backend-1619c',
    authDomain: 'whatsapp-backend-1619c.firebaseapp.com',
    storageBucket: 'whatsapp-backend-1619c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5T8VdGpOtqxt3YW7JhCYcgzIMmsbwwNQ',
    appId: '1:757098419210:android:b00da6a434236ba586fbf3',
    messagingSenderId: '757098419210',
    projectId: 'whatsapp-backend-1619c',
    storageBucket: 'whatsapp-backend-1619c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOe8dDtMCnST_mI8A_flKR85yCQX3fA4',
    appId: '1:757098419210:ios:350dd1229f4bf30986fbf3',
    messagingSenderId: '757098419210',
    projectId: 'whatsapp-backend-1619c',
    storageBucket: 'whatsapp-backend-1619c.appspot.com',
    iosClientId: '757098419210-lpncshvcdppbrptst79i089uqah638bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
